apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-service.name" . }}-sa
  labels:
    app: {{ include "my-service.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "my-service.name" . }}-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "my-service.name" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "my-service.name" . }}-sa
roleRef:
  kind: Role
  name: {{ include "my-service.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
