{{- if .Values.config.githubToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-service.name" . }}-secret
type: Opaque
data:
  githubToken: {{ .Values.config.githubToken | b64enc | quote }}
{{- end }}
